fint:
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: flyt
      instance-retention-ms: 345600000
    application-id: ${fint.application-id}
spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}