package no.fintlabs.integration.error;

public enum ErrorCode {
    GENERAL_SYSTEM_ERROR,
    NO_CONFIGURATION_FOR_INTEGRATION,
    MISSING_INSTANCE_FIELD_FOR_CASE_CONFIGURATION_FIELD,
    MISSING_INSTANCE_FIELD_FOR_RECORD_CONFIGURATION_FIELD,
    MISSING_INSTANCE_FIELD_FOR_DOCUMENT_CONFIGURATION_FIELD,
    MISSING_MAPPING_FIELD_FOR_CASE,
    MISSING_MAPPING_FIELD_FOR_RECORD,
    MISSING_MAPPING_FIELD_FOR_DOCUMENT;

    private static final String ERROR_PREFIX = "FINT_SKJEMA_CASE_SERVICE_";

    public String getCode() {
        return ERROR_PREFIX + name();
    }

}
