apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-egrunnerverv-instance-gateway
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-flyt-egrunnerverv-instance-gateway
    app.kubernetes.io/instance: fint-flyt-egrunnerverv-instance-gateway_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: docker/getting-started
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M'
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }