apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-mapping-service
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-flyt-mapping-service
    app.kubernetes.io/instance: fint-flyt-mapping-service_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-flyt-mapping-service:sha-0000000
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx450M -Xms350M'
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "300Mi"
      cpu: "100m"
  probes:
    startup:
      path: /actuator/health
      port: 8080
      initialDelaySeconds: 70
      failureThreshold: 12
      periodSeconds: 10
      timeoutSeconds: 3
    readiness:
      path: /actuator/health/readiness
      port: 8080
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 3
    liveness:
      path: /actuator/health/liveness
      port: 8080
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 3
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
