name: CD Deploy

on:
  workflow_run:
    workflows:
      - CI Build
    types:
      - completed

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: read

jobs:
  deploy-to-aks:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        org:
          - afk-no
          - agderfk-no
          - bfk-no
          - ffk-no
          - fintlabs-no
          - innlandetfylke-no
          - mrfylke-no
          - nfk-no
          - ofk-no
          - rogfk-no
          - telemarkfylke-no
          - tromsfylke-no
          - trondelagfylke-no
          - vestfoldfylke-no
          - vlfk-no
        cluster:
          - aks-beta-fint-2021-11-23
          - aks-api-fint-2022-02-08
        exclude:
          - org: fintlabs-no
            cluster: aks-api-fint-2022-02-08
          - org: mrfylke-no
            cluster: aks-beta-fint-2021-11-23
          - org: nfk-no
            cluster: aks-beta-fint-2021-11-23

    steps:
      - uses: actions/checkout@v4
      - run: echo "IMAGE_NAME=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}
      - uses: actions/github-script@v7
        id: environment
        with:
          script: return '${{ matrix.cluster }}'.split('-')[1]
          result-encoding: string
      - uses: actions/github-script@v7
        id: resource-group
        with:
          script: return 'rg-aks-${{ steps.environment.outputs.result }}'
          result-encoding: string
      - uses: azure/k8s-bake@v3
        id: bake
        with:
          renderEngine: kustomize
          kustomizationPath: kustomize/overlays/${{ matrix.org }}/${{ steps.environment.outputs.result }}
      - uses: azure/login@v2
        with:
          creds: ${{ secrets[ format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result) ] }}
      - uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.32'
      - uses: azure/aks-set-context@v4
        with:
          cluster-name: ${{ matrix.cluster }}
          resource-group: ${{ steps.resource-group.outputs.result }}
          admin: true
          use-kubelogin: true
      - uses: azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}
          namespace: ${{ matrix.org }}
